name: Build on Push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on: [pull_request]

jobs:
  build_on_pr:
    name: Build On PR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@main

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean verify